import { I18n } from "i18n-js";

export const en = {
  location: "Location",
  search: "Search for something?",
  house: "House",
  apartment: "Apartment",
  hotel: "Hotel",
  nearbyYou: "Nearby you locations",
  recommendedToYou: "Recommended to you",
  month: "month",
  year: "year",
  forSell: "for sell",
  seeMore: "See More",
  profile: "Profile",
  ready: "Ready",
  reviewing: "Reviewing",
  settings: "Settings",
  preferences: "Preferences",
  language: "Language",
  applicationSettings: "Application Settings",
  notifications: "Notifications",
  darkMode: "Dark Mode",
  support: "Support",
  helpCenter: "Help center",
  termsAndConditions: "Terms and conditions",
  balance: "Balance",
  pound: "SD",
  termsAndConditionsApply: "* Terms and conditions apply",
  addBalance: "Add balance",
  activity: "Activity",
  withdrawnFromYourAccount: "Withdrawn from account",
  addedToYourAccount: "Added to account",
};
export const ar = {
  location: "الموقع الحالي",
  search: "تبحث عن شئ معين ؟",
  house: "منزل",
  apartment: "شقة",
  hotel: "فندق",
  nearbyYou: " عروض بالقرب منك",
  recommendedToYou: "الموصى بها لك",
  month: "للشهر",
  year: "للسنة",
  forSell: "بيع",
  seeMore: "المزيد",
  profile: "الصفحة الشخصية",
  ready: "عروضي",
  reviewing: "تحت التقيم",
  settings: "الأعدادات",
  preferences: "التفضيلات",
  language: "اللغة",
  applicationSettings: "اعدادات التطبيق",
  notifications: "الاشعارات",
  darkMode: "الوضع الليلي",
  support: "المساعدة",
  helpCenter: "مركز المساعدة",
  termsAndConditions: "الأحكام والشروط",
  balance: "رصيدي",
  pound: "جنية",
  termsAndConditionsApply: "تطبق الشروط والاحكام *",
  addBalance: "أضافة رصيد",
  activity: "النشاطات",
  withdrawnFromYourAccount: "تم سحب مبلغ من حسابك",
  addedToYourAccount: "تم أضافة مبلغ الى حسابك",
};

export const i18n = new I18n({ en, ar });
